[package]
name = "ksp-cfg-formatter-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
walkdir = "2.3.2"
ksp-cfg-formatter = { path = "../ksp-cfg-formatter" }
stderrlog = "0.5.4"
log = "0.4.20"
anyhow = "1.0.75"
itertools = "0.11.0"
